export const filteredToxins = [
    {"name":"ACE-inhibitors","link":"https://www.petpoisonhelpline.com/poison/ace-inhibitors/","category":"Medications"},
    {"name":"Acetaminophen","link":"https://www.petpoisonhelpline.com/poison/acetaminophen/","category":"medications"},
    {"name":"Acids","link":"https://www.petpoisonhelpline.com/poison/acids/","category":"household items"},
    {"name":"Alcohol","link":"https://www.petpoisonhelpline.com/poison/alcohol/","category":"foods"},
    {"name":"Alkalis","link":"https://www.petpoisonhelpline.com/poison/alkalis/","category":"household items"},
    {"name":"Ambien","link":"https://www.petpoisonhelpline.com/poison/ambien/","category":"medications"},
    {"name":"Amphetamines","link":"https://www.petpoisonhelpline.com/poison/amphetamines/","category":"medications"},
    {"name":"Antibiotics","link":"https://www.petpoisonhelpline.com/poison/antibiotic/","category":"medications"},
    {"name":"Antidepressants","link":"https://www.petpoisonhelpline.com/poison/antidepressants/","category":"medications"},
    {"name":"Antihistamines","link":"https://www.petpoisonhelpline.com/poison/antihistamine/","category":"medications"},
    {"name":"Apricot","link":"https://www.petpoisonhelpline.com/poison/apricot/","category":"foods"},
    {"name":"Aspirin","link":"https://www.petpoisonhelpline.com/poison/aspirin/","category":"medications"},
    {"name":"Asthma Inhaler","link":"https://www.petpoisonhelpline.com/poison/asthma-inhaler/","category":"medications"},
    {"name":"Australian Nut","link":"https://www.petpoisonhelpline.com/poison/australian-nut/","category":"foods"},
    {"name":"Avocado","link":"https://www.petpoisonhelpline.com/poison/avocado/","category":"foods"},
    {"name":"Baclofen","link":"https://www.petpoisonhelpline.com/poison/baclofen/","category":"Medications"},
    {"name":"Batteries","link":"https://www.petpoisonhelpline.com/poison/batteries/","category":"household Items"},
    {"name":"Benzodiazepines","link":"https://www.petpoisonhelpline.com/poison/benzodiazepines/","category":"Medications"},
    {"name":"Beta-blockers","link":"https://www.petpoisonhelpline.com/poison/beta-blockers/","category":"Medications"},
    {"name":"Bread Dough","link":"https://www.petpoisonhelpline.com/poison/bread-dough/","category":"foods"},
    {"name":"Caffeine","link":"https://www.petpoisonhelpline.com/poison/caffeine/","category":"foods"},
    {"name":"Calcipotriene","link":"https://www.petpoisonhelpline.com/poison/calcipotriene/","category":"medications"},
    {"name":"Calcium Channel Blockers","link":"https://www.petpoisonhelpline.com/poison/calcium-channel-blockers/","category":"medications"},
    {"name":"Calcium Supplements","link":"https://www.petpoisonhelpline.com/poison/calcium-supplements/","category":"medications"},
    {"name":"Carprofen","link":"https://www.petpoisonhelpline.com/poison/carprofen/","category":"medications"},
    {"name":"Cherry","link":"https://www.petpoisonhelpline.com/poison/cherry/","category":"foods"},
    {"name":"Chocolate","link":"https://www.petpoisonhelpline.com/poison/chocolate/","category":"foods"},
    {"name":"Coins","link":"https://www.petpoisonhelpline.com/poison/coins/","category":"metals"},
    {"name":"Cough Medicine","link":"https://www.petpoisonhelpline.com/poison/cough-medicine/","category":"medications"},
    {"name":"Currants","link":"https://www.petpoisonhelpline.com/poison/currant/","category":"foods"},
    {"name":"Decongestants","link":"https://www.petpoisonhelpline.com/poison/decongestants/","category":"medications"},
    {"name":"Deramaxx","link":"https://www.petpoisonhelpline.com/poison/deramaxx/","category":"medications"},
    {"name":"Detergents","link":"https://www.petpoisonhelpline.com/poison/detergents/","category":"household items"},
    {"name":"Diuretic","link":"https://www.petpoisonhelpline.com/poison/diuretic/","category":"medications"},
    {"name":"Effexor","link":"https://www.petpoisonhelpline.com/poison/effexor/","category":"Medications"},
    {"name":"EtoGesic","link":"https://www.petpoisonhelpline.com/poison/etogesic/","category":"Medications"},
    {"name":"Firestarter Logs","link":"https://www.petpoisonhelpline.com/poison/firestarter-logs/","category":"household items"},
    {"name":"Fireworks","link":"https://www.petpoisonhelpline.com/poison/fireworks/","category":"household items"},
    {"name":"Firocoxib","link":"https://www.petpoisonhelpline.com/poison/firocoxib/","category":"medications"},
    {"name":"Flea Collar","link":"https://www.petpoisonhelpline.com/poison/flea-collar/","category":"medications"},
    {"name":"Flea and Tick Medications","link":"https://www.petpoisonhelpline.com/poison/flea-and-tick-medication/","category":"medications"},
    {"name":"Fluoride","link":"https://www.petpoisonhelpline.com/poison/fluoride/","category":"household items"},
    {"name":"Garlic","link":"https://www.petpoisonhelpline.com/poison/garlic/","category":"foods"},
    {"name":"Glow Jewelry","link":"https://www.petpoisonhelpline.com/poison/glow-jewelry/","category":"Household items"},
    {"name":"Gorilla Glue","link":"https://www.petpoisonhelpline.com/poison/gorilla-glue/","category":"household items"},
    {"name":"Grapes","link":"https://www.petpoisonhelpline.com/poison/grapes/","category":"foods"},
    {"name":"Hand Sanitizer (Ethanol)","link":"https://www.petpoisonhelpline.com/poison/hand-sanitizer-ethanol/","category":"household items"},
    {"name":"Hand Warmers","link":"https://www.petpoisonhelpline.com/poison/hand-warmers/","category":"metals"},
    {"name":"Hops","link":"https://www.petpoisonhelpline.com/poison/hops/","category":"foods"},
    {"name":"Ibuprofen","link":"https://www.petpoisonhelpline.com/poison/ibuprofen/","category":"medications"},
    {"name":"Imidazoline","link":"https://www.petpoisonhelpline.com/poison/imidazoline/","category":"medications"},
    {"name":"Iron","link":"https://www.petpoisonhelpline.com/poison/iron/","category":"metals"},
    {"name":"Isoniazid","link":"https://www.petpoisonhelpline.com/poison/isoniazid/","category":"medications"},
    {"name":"Ivermectin","link":"https://www.petpoisonhelpline.com/poison/ivermectin/","category":"medications"},
    {"name":"Lead","link":"https://www.petpoisonhelpline.com/poison/lead/","category":"metals"},
    {"name":"Liquid Potpourri","link":"https://www.petpoisonhelpline.com/poison/potpourri-liquid/","category":"household items"},
    {"name":"Lunesta","link":"https://www.petpoisonhelpline.com/poison/lunesta/","category":"medications"},
    {"name":"Macadamia Nuts","link":"https://www.petpoisonhelpline.com/poison/macadamia-nuts/","category":"foods"},
    {"name":"Matches","link":"https://www.petpoisonhelpline.com/poison/matches/","category":"household items"},
    {"name":"Meloxicam","link":"https://www.petpoisonhelpline.com/poison/meloxicam/","category":"medications"},
    {"name":"Methionine","link":"https://www.petpoisonhelpline.com/poison/methionine/","category":"medications"},
    {"name":"Methylphenidate","link":"https://www.petpoisonhelpline.com/poison/methylphenidate/","category":"medications"},
    {"name":"Moldy Food (Mycotoxins)","link":"https://www.petpoisonhelpline.com/poison/mycotoxin/","category":"foods"},
    {"name":"Mothballs","link":"https://www.petpoisonhelpline.com/poison/mothballs/","category":"household items"},
    {"name":"Moxidectin","link":"https://www.petpoisonhelpline.com/poison/moxidectin/","category":"medications"},
    {"name":"Mushrooms","link":"https://www.petpoisonhelpline.com/poison/mushrooms/","category":"foods"},
    {"name":"NSAIDs","link":"https://www.petpoisonhelpline.com/poison/nsaids/","category":"medications"},
    {"name":"Naproxen","link":"https://www.petpoisonhelpline.com/poison/naproxen/","category":"medications"},
    {"name":"Nicotine","link":"https://www.petpoisonhelpline.com/poison/nicotine/","category":"medications"},
    {"name":"Onions","link":"https://www.petpoisonhelpline.com/poison/onion/","category":"foods"},
    {"name":"Opioids & Opiates","link":"https://www.petpoisonhelpline.com/poison/opioids-opiates/","category":"medications"},
    {"name":"Paintballs","link":"https://www.petpoisonhelpline.com/poison/paintballs/","category":"household items"},
    {"name":"Peach Pits","link":"https://www.petpoisonhelpline.com/poison/peach-pits/","category":"foods"},
    {"name":"Phenylpropanolamine","link":"https://www.petpoisonhelpline.com/poison/phenylpropanolamine/","category":"medications"},
    {"name":"Pimobendan","link":"https://www.petpoisonhelpline.com/poison/pimobendan/","category":"medications"},
    {"name":"Pine Oil","link":"https://www.petpoisonhelpline.com/poison/pine-oil/","category":"household items"},
    {"name":"Play Dough (Homemade)","link":"https://www.petpoisonhelpline.com/poison/homemade-play-dough/","category":"foods"},
    {"name":"Potato (Green)","link":"https://www.petpoisonhelpline.com/poison/potato-green/","category":"foods"},
    {"name":"Raisins","link":"https://www.petpoisonhelpline.com/poison/raisins/","category":"foods"},
    {"name":"Salt","link":"https://www.petpoisonhelpline.com/poison/salt/","category":"foods"},
    {"name":"Sleep Aids","link":"https://www.petpoisonhelpline.com/poison/sleep-aids/","category":"medications"},
    {"name":"Star Fruit","link":"https://www.petpoisonhelpline.com/poison/starfruit/","category":"foods"},
    {"name":"Super Glue","link":"https://www.petpoisonhelpline.com/poison/super-glue/","category":"household items"},
    {"name":"Thyroid Medications","link":"https://www.petpoisonhelpline.com/poison/thyroid-medications/","category":"medications"},
    {"name":"Tick Collar","link":"https://www.petpoisonhelpline.com/poison/tick-collar/","category":"medications"},
    {"name":"Tinsel","link":"https://www.petpoisonhelpline.com/poison/tinsel/","category":"household items"},
    {"name":"Vitamins","link":"https://www.petpoisonhelpline.com/poison/vitamins/","category":"medications"},
    {"name":"Xylitol","link":"https://www.petpoisonhelpline.com/poison/xylitol/","category":"foods"},
    {"name":"Zinc","link":"https://www.petpoisonhelpline.com/poison/zinc/","category":"metals"},
    {"name":"5-fluorouracil (5-FU)","link":"https://www.petpoisonhelpline.com/poison/5-fluorouracil/","category":"medications"}
]
